namespace DotNetNottsIot2022.ftdiDotnet;

public enum FT_DEVICE
{
  FT_DEVICE_BM,
  FT_DEVICE_AM,
  FT_DEVICE_100AX,
  FT_DEVICE_UNKNOWN,
  FT_DEVICE_2232,
  FT_DEVICE_232R,
  FT_DEVICE_2232H,
  FT_DEVICE_4232H,
  FT_DEVICE_232H,
  FT_DEVICE_X_SERIES
}
